main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('story1/', views.story1, name='story1'),
    path('story3/', views.story3, name='story3'),
    path('miripstory3/', views.miripstory3, name='miripstory3'),
]

story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story5/', include('story5.urls')),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('', views.inputhtml, name='inputhtml'),
    path('output',views.outputhtml,name='outputhtml'),
]

main/models.py
from django.db import models

# Create your models here.

story5/models.py
from django.db import models

# Create your models here.

from django.utils import timezone
from datetime import datetime, date


class Jadwal(models.Model):
    nama_mata_kuliah = models.CharField(max_length=50)
    dosen_pengajar = models.CharField(max_length=50)
    jumlah_sks = models.CharField(max_length=5)
    deskripsi_mata_kuliah=models.CharField(max_length=150)
    semester_tahun=models.CharField(max_length=20)
    ruang_kelas=models.CharField(max_length=50)


class Post(models.Model):
    Kuliah = models.ForeignKey(Jadwal,null=True, on_delete =models.CASCADE)
    content = models.CharField(max_length=125)
    published_date = models.DateTimeField(default=timezone.now)
    


        

story5/forms.py
from django import forms
from .models import Jadwal

    
class Input_Form(forms.ModelForm):
    class Meta:
        model = Jadwal
        fields = ['nama_mata_kuliah','dosen_pengajar','jumlah_sks','deskripsi_mata_kuliah','semester_tahun','ruang_kelas']
        
    error_messages = {
        'required' : 'Please Type'
    }
    input_attrs = {
        'type' : 'text',
    }  
    nama_mata_kuliah = forms.CharField(label='nama mata kuliah ', required=True, max_length=50, widget=forms.TextInput(attrs=input_attrs))
    dosen_pengajar = forms.CharField(label='nama dosen ', required=True, max_length=50, widget=forms.TextInput(attrs=input_attrs))
    jumlah_sks = forms.CharField(label='jumlah sks ', required=True, max_length=5, widget=forms.TextInput(attrs=input_attrs))
    deskripsi_mata_kuliah = forms.CharField(label='deskripsi mata kuliah ', required=True, max_length=150, widget=forms.TextInput(attrs=input_attrs))
    semester_tahun = forms.CharField(label='semester tahun ', required=True, max_length=20, widget=forms.TextInput(attrs=input_attrs))
    ruang_kelas = forms.CharField(label='ruang kelas ', required=True, max_length=50, widget=forms.TextInput(attrs=input_attrs))
    

main/views.py
from django.shortcuts import render

namaku = "Aldi"
npm = "1906350635"
namadopplegangger = "idla"
npmdopple= "5360536091"
def home(request):
    
    return render(request, 'main/home.html')

def story1(request):
    return render(request, 'main/test.html')

def story3(request):
    respon = {'nama' : namaku,
              'npm' : npm,
              }
    return render(request, 'main/story3.html',respon)

def miripstory3(request):
    respon = {'nama' : namadopplegangger,
              'npm' : npmdopple,
              }
    return render(request, 'main/miripstory 3.html',respon)

story5/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form
from .models import Jadwal,Post

# Create your views here.
def inputhtml(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid and request.method =="POST"):
       form.save()
       return HttpResponseRedirect('')
    else:
       return render(request,'input.html',{'form':form})

def outputhtml(request):
    jadwal = Jadwal.objects.all()
    response = {'jadwal':jadwal}
    html = 'output.html'
    return render(request, html, response)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Homepage sementara</title>
{% endblock meta %}

{% block content %}
  <h1>Silahkan menuju salah satu storyku</h1>
  <nav>
    <a href="{% url 'main:story1' %}">Story1</a>|
    <a href="{% url 'main:story3' %}">Story3</a>|
    <a href="{% url 'main:miripstory3' %}">miripstory3</a>
   </nav>          
{% endblock content %}

main/templates/main/miripstory 3.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{%static 'cssStory3.css'%}" rel="stylesheet" type"text/css">
        <title>Kemabaran profile diriku</title>
    </head>
    
    <body>
        <h1>I'm the dopple gangger</h1>
        <nav>
            <a href="{% url 'main:story1' %}">Story1</a>|
            <a href="{% url 'main:story3' %}">Story3</a>
        </nav>
        
        <hr>
        <div id="myDiv">
        <h2> Data diri</h2>
            <ul>      
            <li>Nama             : {{nama}} </li>
            <li>NPM              : {{npm}}</li>
            <li>Angkatan         : 9102 </li>  
            <li>Tempat Kuliah    :<a href="https://www.ui.ac.id/">Universitas Indonesia  </a></li> 
            <li>Jurusan          : Ilmu Komputer </li>  
            <li>Media Sosial     :<a href="https://www.facebook.com/profile.php?id=100005583944719/">Facebook</a>, <a href="https://www.instagram.com/aladster_tjendana/", style=text-align:right; > Instagram </a></li>    
            <li>id Line          : -</li>                   
            <li> <p>Deskripsi singkat : Saya mencoba meniru aldi
                 <br>
                                          Mencoba adalah sesuatu yang bersifat
                 <br>
                                           Trial and error. Jadi saya akan belajar
                 <br>
                                           kagebunshin no jutsu!</p></li>
            </ul>
            <div id="myDiv2"> 
                <h2> Pengalaman</h2>
                <ul>
                <li id="li1">Paskibra</li>
                <p>Menjadi paskibraka pada tahun 9000
                <br>
                   Mengajar paskibra dan pelaksana upacara. Saya mengajar junior seterusnya.
                <li id="li1">Palang Merah Remaja</li>
                <p>Menjadi anggota PMI
                <br>
                   Saya menguasai teknik bidan dengan baik</p>
                <li id="li1">Mahasiswa UI</li>
                <p> Mahasiswa Fasilkom  UI
                <br>
                   Masuk melalui jalur sbmptn. Menjadi mahasiswa UI tahun 9100 mengambil jurusan ilmu komputer</p>
                <a href="https://smaricci1.sekolahricci.sch.id/"> untuk mencari tahu mengenai <b> Targetku.</b></a>
                </ul>
            </div>    
        </div>
        
        <div id="myDiv3"> 
            <div id="myDiv5">
                <img src="https://picsum.photos/200/100">
                <div id="myDiv6">
                    <h3> This is my picture </h3>
                    <center>
                        <img src="{% static 'img/aladster.jpg' %}">
                    </center>
                </div>
            </div>
            <h2> Hobi</h2>
            <ul>
            <li id="li1">Gamer</li>
            <p>Bermain game sejak kecil. Bermain semua genre game. 
            <br>
            Sangat suka dengan puzzle,fps,tps,mmorpg,adventure,action,dan masih banyak lagi.
            <br>
            Sedang mendalami sekiro dan bermain apex legend</p>
            <a href="https://www.ea.com/games/apex-legends"> untuk mencari tahu mengenai <b> Apex Legends.</b></a>
            <li id="li1">Olahraga</li>
            <p>Bermain basket seminggu sekali. Bisa bermain olahraga lain sebagai orang avarage.
            <br>
            Mencoba semua jenis olahraga walaupun masih obesitas level 2.</p>
            <li id="li1">menikmati pemandangan</li>
            <p>Menikmati alam suka hiking dan berkelana. Alam itu indah.</p>
            <div id="myDiv4">
                <div class="myDiv4">  
                    <h2>Riwayat Pendidikan</h2>
                        <table>
                          <tr>
                            <th id="thTitle">Nama Sekolah</th>
                            <th id="thTitle">Kelas</th> 
                            <th id="thTitle">Tahun</th>
                          </tr>
                          <tr>
                            <td>SD Katorlik Ricci</td>
                            <td>SD</td>
                            <td>9080</td>
                          </tr>
                          <tr>
                            <td>SMP Katolik Ricci</td>
                            <td>SMP</td>
                            <td>9088</td>
                          </tr>
                          <tr>
                            <td>SMA Katolik Ricci</td>
                            <td>SMA</td>
                            <td>9990</td>
                          </tr>
                        </table>
                        <br>
                        <table>
                          <tr>
                            <th id="thTitle">Nama Kegiatan</th>
                            <th id="thTitle">Jabatan</th> 
                            <th id="thTitle">Tahun</th>
                          </tr>
                          <tr>
                            <td>Rival</td>
                            <td>koordinator</td>
                            <td>9099</td>
                          </tr>
                          <tr>
                            <td>Donor darah</td>
                            <td>koordinator</td>
                            <td>9100</td>
                          </tr>
                          <tr>
                            <td>Training camp</td>
                            <td>ketua kegiatan</td>
                            <td>9101</td>
                          </tr>
                        </table>                   
            </div>
        </div>  
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>      
    </body>
</html>
        

main/templates/main/story3.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link href="{%static 'cssStory3.css'%}" rel="stylesheet" type"text/css">
        <title>Profile Diriku</title>       
    </head>
    
    <body>
        <h1>Welcome to My Profile \^-^/</h1>
        <nav>
            <a href="{% url 'main:story1' %}">Story1</a>|
            <a href="{% url 'main:miripstory3' %}">miripstory3</a>
        </nav>
        
        <hr>
        <div id="myDiv">
        <h2> Data diri</h2>
            <ul>      
            <li>Nama             : {{nama}} </li>
            <li>NPM              : {{npm}}</li>
            <li>Angkatan         : 2019 </li>  
            <li>Tempat Kuliah    :<a href="https://www.ui.ac.id/">Universitas Indonesia  </a></li> 
            <li>Jurusan          : Ilmu Komputer </li>  
            <li>Media Sosial     :<a href="https://www.facebook.com/profile.php?id=100005583944719/">Facebook</a>, <a href="https://www.instagram.com/aladster_tjendana/", style=text-align:right; > Instagram </a></li>    
            <li>id Line          : aladster</li>                   
            <li> <p>Deskripsi singkat : Saya senang bermain dan mencoba hal baru.
                 <br>
                                           Pantang menyerah adalah motto saya. Saya
                 <br>
                                           introvert tetapi tidak apa-apa menjadi 
                 <br>
                                           ekstrovert. Jadi mari kita berteman!</p></li>
            </ul>
            <div id="myDiv2"> 
                <h2> Pengalaman</h2>
                <ul>
                <li id="li1">Paskibra</li>
                <p>Menjadi paskibra ricci
                <br>
                   Mengajar paskibra dan pelaksana upacara di ricci tahun 2016-2019
                <li id="li1">Palang Merah Remaja</li>
                <p>Menjadi anggota PMI
                <br>
                   Mengajar PMR di ricci dan menjadi spesialis tandu. Mengikuti lomba membuat tandu 3 kali.</p>
                <li id="li1">Mahasiswa UI</li>
                <p> Mahasiswa Fasilkom  UI
                <br>
                   Masuk melalui jalur sbmptn. Menjadi mahasiswa UI tahun 2019 mengambil jurusan ilmu komputer</p>
                <a href="https://smaricci1.sekolahricci.sch.id/"> untuk mencari tahu mengenai <b> SMA Ricci.</b></a>
                </ul>
            </div>    
        </div>
        
        <div id="myDiv3"> 
            <div id="myDiv5">
                <img src="https://picsum.photos/200/100">
                <div id="myDiv6">
                    <h3> This is my picture </h3>
                    <center>
                        <img src="{% static 'img/aladster.jpg' %}">
                    </center>
                </div>
            </div>
            <h2> Hobi</h2>
            <ul>
            <li id="li1">Gamer</li>
            <p>Bermain game sejak kecil. Bermain semua genre game. 
            <br>
            Sangat suka dengan puzzle,fps,tps,mmorpg,adventure,action,dan masih banyak lagi.
            <br>
            Sedang mendalami sekiro dan bermain apex legend</p>
            <a href="https://www.ea.com/games/apex-legends"> untuk mencari tahu mengenai <b> Apex Legends.</b></a>
            <li id="li1">Olahraga</li>
            <p>Bermain basket seminggu sekali. Bisa bermain olahraga lain sebagai orang avarage.
            <br>
            Mencoba semua jenis olahraga walaupun masih obesitas level 2.</p>
            <li id="li1">menikmati pemandangan</li>
            <p>Menikmati alam suka hiking dan berkelana. Alam itu indah.</p>
            <div id="myDiv4">
                <div class="myDiv4">  
                    <h2>Riwayat Pendidikan</h2>
                        <table>
                          <tr>
                            <th id="thTitle">Nama Sekolah</th>
                            <th id="thTitle">Kelas</th> 
                            <th id="thTitle">Tahun</th>
                          </tr>
                          <tr>
                            <td>SD Katorlik Ricci</td>
                            <td>SD</td>
                            <td>2007-2013</td>
                          </tr>
                          <tr>
                            <td>SMP Katolik Ricci</td>
                            <td>SMP</td>
                            <td>2013-2016</td>
                          </tr>
                          <tr>
                            <td>SMA Katolik Ricci</td>
                            <td>SMA</td>
                            <td>2016-2019</td>
                          </tr>
                        </table>
                        <br>
                        <table>
                          <tr>
                            <th id="thTitle">Nama Kegiatan</th>
                            <th id="thTitle">Jabatan</th> 
                            <th id="thTitle">Tahun</th>
                          </tr>
                          <tr>
                            <td>Rival</td>
                            <td>koordinator</td>
                            <td>2019</td>
                          </tr>
                          <tr>
                            <td>Donor darah</td>
                            <td>koordinator</td>
                            <td>2017-2019</td>
                          </tr>
                          <tr>
                            <td>Training camp</td>
                            <td>ketua kegiatan</td>
                            <td>2015-2018</td>
                          </tr>
                        </table>                   
            </div>
        </div>  
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>      
    </body>
</html>
        

main/templates/main/test.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>My profile for first story</title>
    </head>
    <body style="background-color:violet;">
        <h1 style="color:skyblue; font-family:magneto; font-size:300%; text-align:center;"> Welcome to my first website \^-^/ </h1>  
        <nav>
            <a href="{% url 'main:story3' %}">Story3</a>|
            <a href="{% url 'main:miripstory3' %}">miripstory3</a>
        </nav>          
        <h2 style="color:black; font-family:magneto; font-size:175%; text-align:center;"> This is my picture </h2>
        <center>
        <img src="{% static 'img/aladster.jpg' %}">
        </center>
        <style>
        .myDiv {
          border: 5px outset red;
          background-color: lightblue;
          text-align: left;
          float:left
        }
        .myDiv2 {
          border: 5px outset red;
          background-color: lightgreen;
          text-align: center;
          float:center;
        }
        .myDiv3 {
          border: 5px outset red;
          background-color: orange;
          text-align: left;
          float:right;
        }
        .myDiv4 {
          border: 5px outset red;
          background-color: lightgrey;
          text-align: left;
          
        }
        
        </style>
        <div class="myDiv">
        <p style="color:green;font-size:150%;"> Data diri</p>
            <ul>      
            <p>Nama             : Aldi
            <br>
               NPM              : 1906350635
            <br>
               Angkatan         : 2019
            <br>
               Tempat Kuliah    : Universitas Indonesia 
            <br> 
               Jurusan          : Ilmu Komputer
            <br> 
               Media Sosial     : <a href="https://www.facebook.com/profile.php?id=100005583944719/"> Facebook </a>
            <br>
                                  <a href="https://www.instagram.com/aladster_tjendana/"> Instagram</a>
            <br>
              id Line           : aladster</p>
               
               
            <p>Deskripsi singkat : Saya senang bermain dan mencoba hal baru.
            <br>
                                   Pantang menyerah adalah motto saya. Saya
            <br>
                                   introvert tetapi tidak apa-apa menjadi 
            <br>
                                   ekstrovert. Jadi mari kita berteman UwU</p>
            <a href="https://www.ui.ac.id/"> untuk mencari tahu mengenai <b> Universitas Indonesia.</b></a>
            
            </ul>
            </div>
            
        <div class="myDiv2">  
        <p style="color:green;font-size:150%;"> Pengalaman</p>
         <ul>
            <li style="color:red;">Paskibra</li>
            <p>Menjadi paskibra ricci
            <br>
               Mengajar paskibra dan pelaksana upacara di ricci tahun 2016-2019
            <li style="color:red;">Palang Merah Remaja</li>
            <p>Menjadi anggota PMI
            <br>
               Mengajar PMR di ricci dan menjadi spesialis tandu. Mengikuti lomba membuat tandu 3 kali.</p>
            <li style="color:red;">Mahasiswa UI</li>
            <p> Mahasiswa Fasilkom  UI
            <br>
                Masuk melalui jalur sbmptn. Menjadi mahasiswa UI tahun 2019 mengambil jurusan ilmu komputer</p>
        <a href="https://smaricci1.sekolahricci.sch.id/"> untuk mencari tahu mengenai <b> SMA Ricci.</b></a>
        </ul>
        </div>
        
        <div class="myDiv3"> 
        <p style="color:green;font-size:150%;"> Hobi</p>
        <ul>
        <li style="color:red;">Gamer</li>
        <p>Bermain game sejak kecil. Bermain semua genre game. 
        <br>
        Sangat suka dengan puzzle,fps,tps,mmorpg,adventure,action,dan masih banyak lagi.
        <br>
        Sedang mendalami sekiro dan bermain apex legend</p>
          <a href="https://www.ea.com/games/apex-legends"> untuk mencari tahu mengenai <b> Apex Legends.</b></a>
        <li style="color:red;">Olahraga</li>
        <p>Bermain basket seminggu sekali. Bisa bermain olahraga lain sebagai orang avarage.
        <br>
           Mencoba semua jenis olahraga walaupun masih obesitas level 2.</p>
        <li style="color:red;">menikmati pemandangan</li>
        <p>Menikmati alam suka hiking dan berkelana. Alam itu indah.</p>
        <img src="https://picsum.photos/200/100" width="200" height="100">
        </div>
        
     <style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
}
th {
  text-align: center;
}
</style>
</head>
<div class="myDiv4">  
<body>
<h2>Riwayat Pendidikan</h2>

<table style="width:60%">
  <tr>
    <th style="color:brown; font-family:verdana; font-size:125%; text-align:center;">Nama Sekolah</th>
    <th style="color:brown; font-family:verdana; font-size:125%; text-align:center;">Kelas</th> 
    <th style="color:brown; font-family:verdana; font-size:125%; text-align:center;">Tahun</th>
  </tr>
  <tr>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">SD Katorlik Ricci</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">SD</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">2007-2013</td>
  </tr>
  <tr>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">SMP Katolik Ricci</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">SMP</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">2013-2016</td>
  </tr>
  <tr>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">SMA Katolik Ricci</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">SMA</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">2016-2019</td>
  </tr>
</table>
    </body>
<body>


<h2>Riwayat Kegiatan</h2>

<table style="width:63%">
  <tr>
    <th style="color:brown; font-family:verdana; font-size:125%; text-align:center;">Nama Kegiatan</th>
    <th style="color:brown; font-family:verdana; font-size:125%; text-align:center;">Jabatan</th> 
    <th style="color:brown; font-family:verdana; font-size:125%; text-align:center;">Tahun</th>
  </tr>
  <tr>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">Rival</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">koordinator</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">2019</td>
  </tr>
  <tr>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">Donor darah</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">koordinator</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">2017-2019</td>
  </tr>
  <tr>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">Training camp</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">ketua kegiatan</td>
    <td style="color:red; font-family:verdana; font-size:80%; text-align:center;">2015-2018</td>
  </tr>
</table>
<p style="text-align:center"> Saat ini Saya sedang belajar di Universitas Indonesia untuk meraih sarjana</p>
<p style="text-align:center"> Jika ingin berkenalan saya akan berada di pacil ^-^</p>
<p style="text-align:center"> Sampai bertemu teman-teman!</p>
</body>
</div>
</html>

story5/templates/base.html
<!DOCTYPE html>
<html>
    <body>
        <nav>
            <a href="{% url 'story5:inputhtml' %}">Input</a>|
            <a href="{% url 'story5:outputhtml' %}">Output</a>
        </nav>
    </body>
<html>

story5/templates/input.html
<!DOCTYPE html>


{% load static %}
<html>
    <head>
        {% block meta %}
            <title>input story5</title>
        {% endblock meta %}
    </head>
    {% block content %}
    <body>
        <nav>
            <a href="{% url 'story5:inputhtml' %}">Input</a>|
            <a href="{% url 'story5:outputhtml' %}">Output</a>
      </nav>
      <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </body>     
    {% endblock content %}  
</html>

story5/templates/output.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        {% block meta %}
            <title>output story5</title>
        {% endblock meta %}
    </head>
    {% block content %}
    <body>
      <nav>
            <a href="{% url 'story5:inputhtml' %}">Input</a>|
            <a href="{% url 'story5:outputhtml' %}">Output</a>
      </nav>
        <table style="width:100%">
            <tr>
                <th> nama mata kuliah </th>
                <th> dosen pengajar </th>
                <th> jumlah sks </th>
                <th> semester tahun </th>
                <th> ruang kelas </th>
            <tr>
            {% if jadwal %}
            {% for kuliah in jadwal %}
            <tr>
                <td>{{ kuliah.nama_mata_kuliah}}</td>
                <td>{{ kuliah.dosen_pengajar}}</td>
                <td>{{kuliah.jumlah_sks}}</td>
                <td>{{kuliah.semester_tahun}}</td>
                <td>{{kuliah.ruang_kelas}}</td>           
            </tr
            {% endfor %}
        {% endif %}
    </body>     
    {% endblock content %}  
</html>